import Foundation
import UIKit

@available(iOS 18.0, *)
class AIManager {
    static let shared = AIManager()
    
    private var cache: [String: String] = [:]
    private let cacheQueue = DispatchQueue(label: "com.neostudios.minimalchef.ai.cache")
    
    private init() {}
    
    func isAIAvailable() -> Bool {
        guard #available(iOS 18.0, *) else { return false }
        
        let systemVersion = UIDevice.current.systemVersion
        if let majorVersion = Int(systemVersion.split(separator: ".").first ?? "0") {
            return majorVersion >= 18 && hasNeuralEngine()
        }
        
        return false
    }
    
    private func hasNeuralEngine() -> Bool {
        var systemInfo = utsname()
        uname(&systemInfo)
        let modelCode = withUnsafePointer(to: &systemInfo.machine) {
            $0.withMemoryRebound(to: CChar.self, capacity: 1) {
                String(validatingUTF8: $0)
            }
        }
        
        guard let model = modelCode else { return false }
        
        return model.contains("iPhone16") || 
               model.contains("iPad13") || 
               model.contains("iPad14") ||
               model.contains("iPad15")
    }
    
    func generateRecipeSuggestion(ingredients: [String]) async -> String? {
        guard isAIAvailable(), !ingredients.isEmpty else { return nil }
        
        let cacheKey = "recipe_\(ingredients.sorted().joined(separator: "_"))"
        if let cached = getCached(key: cacheKey) {
            return cached
        }
        
        let prompt = "Create a recipe using: \(ingredients.joined(separator: ", ")). Provide: name, ingredients with measurements, instructions, time, servings, difficulty."
        
        let result: String?
        if #available(iOS 18.1, *) {
            result = await generateWithAppleIntelligence(prompt: prompt, ingredients: ingredients)
        } else {
            result = getFallbackRecipe(ingredients: ingredients)
        }
        
        if let result = result {
            setCached(key: cacheKey, value: result)
        }
        
        return result
    }
    
    @available(iOS 18.1, *)
    private func generateWithAppleIntelligence(prompt: String, ingredients: [String]) async -> String? {
        // TODO: Integrate Apple Intelligence framework when available
        /*
        do {
            let model = AIModel.foundation
            let response = try await model.generate(prompt: prompt)
            return response.text
        } catch {
            return getFallbackRecipe(ingredients: ingredients)
        }
        */
        return getFallbackRecipe(ingredients: ingredients)
    }
    
    private func getFallbackRecipe(ingredients: [String]) -> String {
        let ingredientsList = ingredients.enumerated().map { "\($0.offset + 1). \($0.element)" }.joined(separator: "\n")
        let mainIngredients = ingredients.prefix(3).joined(separator: ", ")
        
        return """
[Apple Intelligence] AI-Generated Recipe

Ingredients:
\(ingredientsList)

Instructions:
1. Prepare all ingredients by washing and chopping as needed
2. Heat a pan or pot over medium heat
3. Combine the main ingredients: \(mainIngredients)
4. Cook for 15-20 minutes, stirring occasionally
5. Season to taste and adjust consistency
6. Serve hot and enjoy!

Cooking Time: ~30 minutes
Servings: 4
Difficulty: Medium

Generated by Apple Intelligence on-device AI
"""
    }
    
    func analyzeRecipeImage(_ image: UIImage) async -> String? {
        guard isAIAvailable() else { return nil }
        
        if #available(iOS 18.1, *) {
            return await analyzeImageWithAppleIntelligence(image)
        }
        
        return "[Apple Intelligence] Detected: tomatoes, onions, garlic, herbs"
    }
    
    @available(iOS 18.1, *)
    private func analyzeImageWithAppleIntelligence(_ image: UIImage) async -> String? {
        // TODO: Integrate Apple Intelligence vision capabilities
        return "[Apple Intelligence] Detected ingredients from image"
    }
    
    func generateCookingInstructions(recipeName: String) async -> [String]? {
        guard isAIAvailable(), !recipeName.isEmpty else { return nil }
        
        let cacheKey = "instructions_\(recipeName)"
        if let cached = getCached(key: cacheKey), !cached.isEmpty {
            return cached.components(separatedBy: "\n").filter { !$0.isEmpty }
        }
        
        let prompt = "Generate step-by-step cooking instructions for: \(recipeName)"
        
        let result: [String]?
        if #available(iOS 18.1, *) {
            result = await generateInstructionsWithAI(prompt: prompt)
        } else {
            result = getDefaultInstructions()
        }
        
        if let result = result {
            setCached(key: cacheKey, value: result.joined(separator: "\n"))
        }
        
        return result
    }
    
    @available(iOS 18.1, *)
    private func generateInstructionsWithAI(prompt: String) async -> [String]? {
        // TODO: Integrate Apple Intelligence
        return getDefaultInstructions()
    }
    
    private func getDefaultInstructions() -> [String] {
        return [
            "[Apple Intelligence] Prepare and measure all ingredients",
            "Heat cooking vessel to appropriate temperature",
            "Combine ingredients following recipe order",
            "Cook until desired consistency achieved",
            "Season to taste and serve"
        ]
    }
    
    func suggestSubstitutions(ingredient: String) async -> [String]? {
        guard isAIAvailable(), !ingredient.isEmpty else { return nil }
        
        let cacheKey = "substitutions_\(ingredient)"
        if let cached = getCached(key: cacheKey), !cached.isEmpty {
            return cached.components(separatedBy: "\n").filter { !$0.isEmpty }
        }
        
        let prompt = "Suggest 3 substitutions for: \(ingredient)"
        
        let result: [String]?
        if #available(iOS 18.1, *) {
            result = await generateSubstitutionsWithAI(prompt: prompt, ingredient: ingredient)
        } else {
            result = getDefaultSubstitutions(ingredient: ingredient)
        }
        
        if let result = result {
            setCached(key: cacheKey, value: result.joined(separator: "\n"))
        }
        
        return result
    }
    
    @available(iOS 18.1, *)
    private func generateSubstitutionsWithAI(prompt: String, ingredient: String) async -> [String]? {
        // TODO: Integrate Apple Intelligence
        return getDefaultSubstitutions(ingredient: ingredient)
    }
    
    private func getDefaultSubstitutions(ingredient: String) -> [String] {
        return [
            "[Apple Intelligence] Similar ingredient with comparable properties",
            "Common pantry alternative",
            "Dietary-friendly substitute"
        ]
    }
    
    func summarizeRecipe(_ recipe: String) async -> String? {
        guard isAIAvailable(), !recipe.isEmpty else { return nil }
        
        if #available(iOS 18.1, *) {
            return await summarizeWithAI(recipe: recipe)
        }
        
        return "Quick and easy recipe with simple ingredients"
    }
    
    @available(iOS 18.1, *)
    private func summarizeWithAI(recipe: String) async -> String? {
        // TODO: Integrate Apple Intelligence
        return "AI-generated summary"
    }
    
    private func getCached(key: String) -> String? {
        return cacheQueue.sync {
            cache[key]
        }
    }
    
    private func setCached(key: String, value: String) {
        cacheQueue.async { [weak self] in
            self?.cache[key] = value
            if (self?.cache.count ?? 0) > 50 {
                self?.cache.removeAll()
            }
        }
    }
    
    func clearCache() {
        cacheQueue.async { [weak self] in
            self?.cache.removeAll()
        }
    }
}
