// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACPLnwKXkxnQPTf_XFJUxpGeuSKEFEN-I',
    appId: '1:409860921755:web:8783d9ec990d9660e3e93e',
    messagingSenderId: '409860921755',
    projectId: 'minimal-chef',
    authDomain: 'minimal-chef.firebaseapp.com',
    storageBucket: 'minimal-chef.firebasestorage.app',
    measurementId: 'G-Z18SLLER2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCYTDvblRKmNa4CbDcbzyBZ3h3p2F2YE',
    appId: '1:409860921755:android:41c8f899c0fd4fa3e3e93e',
    messagingSenderId: '409860921755',
    projectId: 'minimal-chef',
    storageBucket: 'minimal-chef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRIcuxbO4kCPSEaTqq7qyyhcAusPIZCKE',
    appId: '1:409860921755:ios:889d5278729bc83de3e93e',
    messagingSenderId: '409860921755',
    projectId: 'minimal-chef',
    storageBucket: 'minimal-chef.firebasestorage.app',
    iosClientId: '409860921755-kjgtpg5cj9gc26pheqsip24p4bbsc115.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimalChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRIcuxbO4kCPSEaTqq7qyyhcAusPIZCKE',
    appId: '1:409860921755:ios:889d5278729bc83de3e93e',
    messagingSenderId: '409860921755',
    projectId: 'minimal-chef',
    storageBucket: 'minimal-chef.firebasestorage.app',
    iosClientId: '409860921755-kjgtpg5cj9gc26pheqsip24p4bbsc115.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimalChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACPLnwKXkxnQPTf_XFJUxpGeuSKEFEN-I',
    appId: '1:409860921755:web:f075d171545d3ec2e3e93e',
    messagingSenderId: '409860921755',
    projectId: 'minimal-chef',
    authDomain: 'minimal-chef.firebaseapp.com',
    storageBucket: 'minimal-chef.firebasestorage.app',
    measurementId: 'G-4Q15TWR4ZY',
  );

}