import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user',
    },
  ],
  developerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'developer',
    },
  ],
};

export default sidebars;